version: "3"

volumes:
    humans_volume:
    media_volume:
    nginx_log_volume:

networks:
    nginx_network:
      driver: bridge
    db_network:
      driver: bridge

services:
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres
        volumes: 
            - humans_volume:/var/lib/postgresql/data
        networks:
            - db_network
        

    humans_api:
        build: ./
        restart: always
        environment:
            SECRET_KEY: my_secret_key
            DB_NAME: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: db
            DJANGO_SETTINGS_MODULE: humans_api.settings.production
            ALLOWED_HOSTS: 'localhost,127.0.0.1,192.168.10.10,5.189.74.8'
        volumes:
            - media_volume:/var/local/humans_api/media
        depends_on:
            - db
        networks:
            - nginx_network
            - db_network
    
    web:
        image: nginx
        restart: always
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - media_volume:/var/local/humans_api/media
            - nginx_log_volume:/var/log/nginx/
        ports:
            - "8080:80"
        depends_on:
            - humans_api
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=8080
            - API_PORT=8000
        networks:
            - nginx_network
        
            