# Generated by Django 3.0.5 on 2020-04-16 13:58

from django.db import migrations, models
import human.models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveIntegerField(validators=[human.models.validate_age], verbose_name='Age'),
        ),
    ]
